CREATE TABLE t_user
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT NOT NULL UNIQUE,
    PASSWORD    TEXT NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME,
    NOTE        TEXT
);

CREATE TRIGGER update_t_user
    AFTER UPDATE
    ON t_user
    FOR EACH ROW
BEGIN
    UPDATE t_user
    SET UPDATE_TIME = CURRENT_TIMESTAMP
    WHERE ID = OLD.ID;
END;


CREATE TABLE t_setting_default
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    CONTENT     TEXT NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME,
    NOTE        TEXT
);

CREATE TRIGGER update_t_setting_default
    AFTER UPDATE
    ON t_setting_default
    FOR EACH ROW
BEGIN
    UPDATE t_setting_default
    SET UPDATE_TIME = CURRENT_TIMESTAMP
    WHERE ID = OLD.ID;
END;


CREATE TABLE t_setting
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID     INTEGER,
    GENERIC     TEXT NOT NULL,
    LLM         TEXT NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME,
    NOTE        TEXT,
);

CREATE TRIGGER update_t_setting
    AFTER UPDATE
    ON t_setting
    FOR EACH ROW
BEGIN
    UPDATE t_setting
    SET UPDATE_TIME = CURRENT_TIMESTAMP
    WHERE ID = OLD.ID;
END;

CREATE TABLE t_provider
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID       INTEGER,
    PROVIDER_NAME TEXT NOT NULL,
    MODEL_NAME    TEXT NOT NULL,
    MODEL_TYPE    TEXT NOT NULL,
    CONFIG        TEXT NOT NULL,
    CREATE_TIME   DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME   DATETIME,
    NOTE          TEXT,
)

CREATE TABLE t_template_default
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT NOT NULL,
    CONTEXT     TEXT NOT NULL,
    CONFIG      TEXT NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME,
    NOTE        TEXT
);

CREATE TRIGGER update_t_template_default
    AFTER UPDATE
    ON t_template_default
    FOR EACH ROW
BEGIN
    UPDATE t_template_default
    SET UPDATE_TIME = CURRENT_TIMESTAMP
    WHERE ID = OLD.ID;
END;


CREATE TABLE t_template
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID     INTEGER,
    NAME        TEXT NOT NULL,
    CONTEXT     TEXT NOT NULL,
    CONFIG      TEXT NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME,
    NOTE        TEXT
);

CREATE TRIGGER update_t_template
    AFTER UPDATE
    ON t_template
    FOR EACH ROW
BEGIN
    UPDATE t_template
    SET UPDATE_TIME = CURRENT_TIMESTAMP
    WHERE ID = OLD.ID;
END;